packages:
  - '.'
  - 'frontend'
  - 'plugins/*'

allowBuilds:
  cpu-features: true
  esbuild: true
  oracledb: true
  protobufjs: true
  sqlite3: true
  ssh2: true

approvedBuilds:
  - better-sqlite3
  - esbuild
  - cpu-features
  - oracledb
  - protobufjs
  - ssh2
  - sqlite3
ignoredBuiltDependencies: []
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - cpu-features
  - oracledb
  - protobufjs
  - sqlite3
  - ssh2
