packages:
  - '.'
  - 'frontend'

allowBuilds:
  cpu-features: set this to true or false
  esbuild: set this to true or false
  oracledb: set this to true or false
  protobufjs: set this to true or false
  sqlite3: set this to true or false
  ssh2: set this to true or false

approvedBuilds:
  - better-sqlite3
ignoredBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
onlyBuiltDependencies:
  - better-sqlite3
